# general setting
name: sms_faust
backend: dp # DataParallel
type: SpectralMeetsSpatialModel
num_gpu: auto
manual_seed: 1234
non-isometric: false
pose_timestep: 0
pose_milestones:
  2: 2
  4: 4
  6: 6

# path
path:
  resume_state: ~

# datasets
datasets:
  train_dataset:
    name: Train
    type: PairFaustDataset
    data_root: ../data/FAUST_aligned/
    phase: train
    return_evecs: True
    return_faces: True
    num_evecs: 300
    return_corr: False
    return_dist: False
  test_dataset:
    name: Test
    type: PairFaustDataset
    data_root: ../data/FAUST_aligned/
    phase: test
    return_evecs: True
    return_faces: True
    num_evecs: 300
    return_corr: True
    return_dist: True
  # setting for train dataset
  batch_size: 1
  num_worker: 16

# network setting
networks:
  feature_extractor:
    type: DiffusionNet
    in_channels: 128
    out_channels: 384
    cache_dir: ../data/FAUST_aligned/diffusion
    input_type: wks
  fmap_net:
    type: RegularizedFMNet
    bidirectional: true
  permutation:
    type: Similarity
    tau: 0.07
  interpolator:
    type: ResnetECPos
    c_dim: 3
    dim: 7
    hidden_dim: 128

# training setting
train:
  total_epochs: 10
  optims:
    feature_extractor:
      type: Adam
      lr: 1.0e-3
    interpolator:
      type: Adam
      lr: 1.0e-3
  schedulers:
    feature_extractor:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 10
    interpolator:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 10
  losses:
    surfmnet_loss:
      type: SURFMNetLoss
      w_bij: 1.0
      w_orth: 1.0
      w_lap: 0.0
    couple_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 1.0
    align_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 5.0
    arap_loss:
      type: ArapLoss
      loss_weight: 100.0
    symmetry_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 1.0
    dirichlet_loss:
      type: DirichletLoss
      loss_weight: 2.0

# validation setting
val:
  val_freq: 4000
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

# log setting
logger:
  print_freq: 20
  save_checkpoint_freq: 4000
